### ISSUE TITLE
importError: cannot import name Module

### ISSUE THREAD

**Issue by museghost** [maxcountryman/flask-uploads#1]
when using flask-uploads, the following is occurred.
(for security problem, I removed folder names of my project with xxxx)
Also, I am using Flask 0.11.dev.

Could you please investigate this issue ?  Maybe... "Module" could be removed or not ?

``` bash
  File "/Users/xxxx/venv/xxxx/lib/python2.7/site-packages/flask/exthook.py", line 81, in load_module
    reraise(exc_type, exc_value, tb.tb_next)
  File "/Users/xxxx/venv/xxxx/lib/python2.7/site-packages/flask_uploads.py", line 24, in <module>
    from flask import current_app, Module, send_from_directory, abort, url_for
ImportError: cannot import name Module
```

**Comment by muggin** [comment]
I also encountered this problem with Flask 0.11, it does not happen in version  0.10.1

**Comment by stlehmann** [comment]
Same for me using Flask 0.11.1, Flask-Uploads 0.2.0 and Python3

``` python
  Traceback (most recent call last):
    File "manage.py", line 4, in <module>
      from app import create_app, db
    File "/home/xxx/app/__init__.py", line 5, in <module>
      from flask.ext.uploads import UploadSet, IMAGES, configure_uploads, \
    File "/home/xxx/venv/lib/python3.4/site-packages/flask/exthook.py", line 96, in load_module
      reraise(exc_type, exc_value, tb.tb_next)
    File "/home/xxx/venv/lib/python3.4/site-packages/flask/_compat.py", line 32, in reraise
      raise value.with_traceback(tb)
    File "/home/xxx/venv/lib/python3.4/site-packages/flask_uploads.py", line 24, in <module>
      from flask import current_app, Module, send_from_directory, abort, url_for
  ImportError: cannot import name 'Module
```

**Comment by maxcountryman** [comment]
Yep this is fixed on master. We just need to do a release. Hang tight.

**Comment by xGlorify** [comment]
I am currently running Flask-Uploads 0.8.0 and Flask 0.11.1 and still getting this error;
`ImportError: cannot import name Module`

Any suggestions?

Edit: Got it to run my remove the Module import in `/usr/local/lib/python2.7/dist-packages/flask_uploads.py`

**Comment by stlehmann** [comment]
Did you use the Version from PyPi? Then try to clone the github repository and install it.

**Comment by proximous** [comment]
I used the following to fix it:
`sudo sed -i 's/app, Module,/app,/' /usr/local/lib/python2.7/dist-packages/flask_uploads.py`

Any schedule for when the new release will be available on PyPi?
